// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PositiveQuote.Data;

namespace PositiveQuote.Migrations
{
    [DbContext(typeof(PositiveQuoteAppDBContext))]
    [Migration("20210621110955_initial V2")]
    partial class initialV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PositiveQuote.Model.Quote", b =>
                {
                    b.Property<int>("Quote_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Quote_Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Quote_ID");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("PositiveQuote.Model.Speaker", b =>
                {
                    b.Property<int>("Speaker_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Speaker_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Speaker_ID");

                    b.ToTable("Speakers");
                });
#pragma warning restore 612, 618
        }
    }
}
